apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app.kubernetes.io/name: catalog-service
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: ClusterIP
