apiVersion: v1
kind: Service
metadata:
  name: config-server-service
spec:
  selector:
    app.kubernetes.io/name: config-server-service
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  type: ClusterIP
