apiVersion: v1
kind: Service
metadata:
  name: purchase-service
spec:
  selector:
    app.kubernetes.io/name: purchase-service
  ports:
  - protocol: TCP
    port: 7500
    targetPort: 7500
  type: ClusterIP
