apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
spec:
  selector:
    app.kubernetes.io/name: zipkin-service
  ports:
  - protocol: TCP
    port: 9411
    targetPort: 9411
  type: ClusterIP
