apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalog-service
    spec:
      containers:
        - name: catalog
          image: catalog:1
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
              name: catalog-port
          env:
            - name: EUREKA_URI
              value: http://eurekaservice:8761/eureka
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://config-serevice:8888
            - name: ZIPKIN_URI
              value: http://zipkin-service:9411/api/v2/spans